# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{whoa}
  s.version = "0.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["richmolj@gmail.com"]
  s.date = %q{2010-03-21}
  s.description = %q{Basic CRUD actions through an AR-style interface. Start/Stop experiments, get tracking snippets, add pages, etc.}
  s.email = %q{lrichmond@customink.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/whoa.rb",
     "lib/whoa/authentication.rb",
     "lib/whoa/experiment.rb",
     "lib/whoa/feed.rb",
     "lib/whoa/link.rb",
     "lib/whoa/page.rb",
     "lib/whoa/request.rb",
     "lib/whoa/wo_object.rb",
     "test/helper.rb",
     "test/test_whoa.rb",
     "whoa.gemspec"
  ]
  s.homepage = %q{http://github.com/richmolj/whoa}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Active-Recordy API to the Google Website Optimizer API (WO)}
  s.test_files = [
    "test/helper.rb",
     "test/test_whoa.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<happymapper>, [">= 0.3.0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 1.4.2"])
      s.add_runtime_dependency(%q<active_support>, [">= 2.3.0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<happymapper>, [">= 0.3.0"])
      s.add_dependency(%q<rest-client>, [">= 1.4.2"])
      s.add_dependency(%q<active_support>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<happymapper>, [">= 0.3.0"])
    s.add_dependency(%q<rest-client>, [">= 1.4.2"])
    s.add_dependency(%q<active_support>, [">= 2.3.0"])
  end
end

